CREATE TABLE IF NOT EXISTS User(
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(32) NOT NULL UNIQUE,
    password VARCHAR(64) NOT NULL DEFAULT 'project443'
);

INSERT IGNORE INTO USER(name) VALUES
    ('ikushima naoya'),
    ('nakayama tomomi'),
    ('shinhama ryota'),
    ('taisho ayumu'),
    ('wakamatsu rei'),
    ('yaguchi akitaka'),
    ('yamakawa sohei'),
    ('fukao kentaro'),
    ('hanamoto nagi'),
    ('kiuchi masahiro'),
    ('matsumura yuma'),
    ('sembu noah'),
    ('shimazaki yuto'),
    ('shiraki daiki'),
    ('sonobe masaya'),
    ('sugahara shigetaka'),
    ('takeda masayoshi'),
    ('tani yuki'),
    ('aichi mariko'),
    ('fujiwara kota'),
    ('imamoto yu'),
    ('izawa shin'),
    ('kishigami kazuki'),
    ('konishi kyosuke'),
    ('kuribayashi takumi'),
    ('masuda naohiro'),
    ('morihara ryoto'),
    ('murozuka shota'),
    ('nishibayashi tatsuki'),
    ('oka hayato'),
    ('sakabe kentaro'),
    ('sekiguchi yuki'),
    ('tanaka haruto'),
    ('yamaguchi haruka');