CREATE TABLE IF NOT EXISTS User(
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(32) unique NOT NULL,
    password VARCHAR(64) NOT NULL DEFAULT 'project443'
);

INSERT IGNORE INTO USER(name) VALUES
    ('konishi kyosuke'),
    ('izawa shin');

CREATE TABLE IF NOT EXISTS Task(
    id INT AUTO_INCREMENT PRIMARY KEY,
    task_name VARCHAR(64) NOT NULL,
    author_name VARCHAR(32) NOT NULL FOREIGN KEY REFERENCES USER(name),
    target_name VARCHAR(32) NOT NULL FOREIGN KEY REFERENCES User(name),
    deadline DATE NOT NULL
)